#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# Default values
DEFAULT_DOMAIN="example.com"
DEFAULT_DATA_DIR="/opt/stack"

# Management subnet default for UISP/Unifi GUI (empty means "no restriction")
DEFAULT_MGMT_SUBNET=""

# =========================
# Custom project management
# =========================

PROJECTS_FILE="$SCRIPT_DIR/.custom_projects"
OVERRIDE_FILE="$SCRIPT_DIR/compose.override.yml"

# Read a scalar value from a simple key: value YAML file
yaml_get() {
    local file="$1" key="$2"
    grep "^${key}:" "$file" 2>/dev/null | sed "s/^${key}: *//" | tr -d '\r'
}

# Regenerate compose.override.yml from .custom_projects
generate_override() {
    if [[ ! -f "$PROJECTS_FILE" ]] || [[ ! -s "$PROJECTS_FILE" ]]; then
        [[ -f "$OVERRIDE_FILE" ]] && rm "$OVERRIDE_FILE"
        info "No custom projects registered; compose.override.yml removed"
        return
    fi

    local caddy_nets="" net_defs="" includes=""

    while IFS= read -r proj || [[ -n "$proj" ]]; do
        [[ -z "$proj" ]] && continue
        local rel="${proj#./}"
        local manifest="$SCRIPT_DIR/$rel/homelab.yml"

        if [[ ! -f "$manifest" ]]; then
            warn "Missing homelab.yml in $proj — skipping"
            continue
        fi

        local net; net=$(yaml_get "$manifest" "backend_network")
        local cfile; cfile=$(yaml_get "$manifest" "compose")

        if [[ -n "$net" ]]; then
            caddy_nets+="      - ${net}"$'\n'
            net_defs+="  ${net}:"$'\n'
            net_defs+="    driver: bridge"$'\n'
            net_defs+="    external: false"$'\n'
            net_defs+="    internal: true"$'\n'
            net_defs+="    name: ${net}"$'\n'
        fi
        [[ -n "$cfile" ]] && includes+="  - path: ${proj}/${cfile}"$'\n'
    done < "$PROJECTS_FILE"

    {
        printf '# Auto-generated by setup.sh. Do not edit manually.\n'
        printf '# To manage custom projects: ./setup.sh --add-project <path>\n'
        printf '\n'

        if [[ -n "$caddy_nets" ]]; then
            printf 'services:\n'
            printf '  caddy:\n'
            printf '    networks:\n'
            printf '%s' "$caddy_nets"
            printf '\n'
            printf 'networks:\n'
            printf '%s' "$net_defs"
            printf '\n'
        fi

        if [[ -n "$includes" ]]; then
            printf 'include:\n'
            printf '%s' "$includes"
        fi
    } > "$OVERRIDE_FILE"

    info "Generated compose.override.yml"
}

# Copy caddy snippets for all registered projects into DATA_DIR/caddy/conf.d/
deploy_caddy_snippets() {
    local data_dir="$1"
    [[ -z "$data_dir" ]] && return
    [[ -f "$PROJECTS_FILE" ]] || return

    sudo mkdir -p "$data_dir/caddy/conf.d"

    while IFS= read -r proj || [[ -n "$proj" ]]; do
        [[ -z "$proj" ]] && continue
        local rel="${proj#./}"
        local manifest="$SCRIPT_DIR/$rel/homelab.yml"
        [[ ! -f "$manifest" ]] && continue

        local name; name=$(yaml_get "$manifest" "name")
        local snippet; snippet=$(yaml_get "$manifest" "caddy_snippet")
        [[ -z "$snippet" ]] && continue

        local src="$SCRIPT_DIR/$rel/$snippet"
        if [[ ! -f "$src" ]]; then
            warn "Caddy snippet not found: $src"
            continue
        fi

        sudo install -m 0644 -o root -g root "$src" "$data_dir/caddy/conf.d/${name}.caddy"
        info "Installed caddy snippet: conf.d/${name}.caddy"
    done < "$PROJECTS_FILE"
}

cmd_add_project() {
    local proj_path="$1"
    [[ -z "$proj_path" ]] && error "--add-project requires a path argument"

    # Normalise to a ./relative path from SCRIPT_DIR
    local rel
    rel=$(realpath --relative-to="$SCRIPT_DIR" "$proj_path" 2>/dev/null) || rel="$proj_path"
    [[ "$rel" != ./* ]] && rel="./$rel"

    local manifest_rel="${rel#./}"
    local manifest="$SCRIPT_DIR/$manifest_rel/homelab.yml"
    [[ ! -f "$manifest" ]] && error "No homelab.yml found in $proj_path"

    # Guard against duplicates
    if [[ -f "$PROJECTS_FILE" ]] && grep -qxF "$rel" "$PROJECTS_FILE"; then
        warn "Project already registered: $rel"
    else
        echo "$rel" >> "$PROJECTS_FILE"
        info "Registered project: $rel"
    fi

    generate_override

    # Deploy caddy snippet if DATA_DIR is known
    local data_dir=""
    if [[ -f "$SCRIPT_DIR/.env" ]]; then
        data_dir=$(grep "^DATA_DIR=" "$SCRIPT_DIR/.env" | cut -d= -f2)
    fi
    if [[ -n "$data_dir" ]]; then
        deploy_caddy_snippets "$data_dir"
    else
        warn "No .env found — caddy snippet not deployed. Run ./setup.sh first, then re-run --add-project."
    fi

    local name; name=$(yaml_get "$manifest" "name")
    local subdomain; subdomain=$(yaml_get "$manifest" "subdomain")

    echo
    info "Project '$name' added."
    if [[ -n "$data_dir" && -n "$subdomain" ]]; then
        local domain=""
        domain=$(grep "^BASE_DOMAIN=" "$SCRIPT_DIR/.env" | cut -d= -f2)
        [[ -n "$domain" ]] && echo "  URL: https://${subdomain}.${domain}"
    fi
    echo "  Restart the stack to apply: docker compose up -d"
}

cmd_remove_project() {
    local proj_path="$1"
    [[ -z "$proj_path" ]] && error "--remove-project requires a path argument"

    local rel
    rel=$(realpath --relative-to="$SCRIPT_DIR" "$proj_path" 2>/dev/null) || rel="$proj_path"
    [[ "$rel" != ./* ]] && rel="./$rel"

    if [[ ! -f "$PROJECTS_FILE" ]] || ! grep -qxF "$rel" "$PROJECTS_FILE"; then
        warn "Project not registered: $rel"
        exit 0
    fi

    local tmp; tmp=$(mktemp)
    grep -vxF "$rel" "$PROJECTS_FILE" > "$tmp" && mv "$tmp" "$PROJECTS_FILE"
    info "Unregistered project: $rel"

    # Remove caddy snippet from DATA_DIR if possible
    local data_dir=""
    if [[ -f "$SCRIPT_DIR/.env" ]]; then
        data_dir=$(grep "^DATA_DIR=" "$SCRIPT_DIR/.env" | cut -d= -f2)
    fi
    if [[ -n "$data_dir" ]]; then
        local rel_inner="${rel#./}"
        local manifest="$SCRIPT_DIR/$rel_inner/homelab.yml"
        if [[ -f "$manifest" ]]; then
            local name; name=$(yaml_get "$manifest" "name")
            local snippet_dest="$data_dir/caddy/conf.d/${name}.caddy"
            if [[ -f "$snippet_dest" ]]; then
                sudo rm "$snippet_dest"
                info "Removed caddy snippet: conf.d/${name}.caddy"
            fi
        fi
    fi

    generate_override

    echo
    echo "Project removed. Restart the stack to apply: docker compose up -d"
}

cmd_list_projects() {
    if [[ ! -f "$PROJECTS_FILE" ]] || [[ ! -s "$PROJECTS_FILE" ]]; then
        echo "No custom projects registered."
        return
    fi
    echo "Registered custom projects:"
    while IFS= read -r proj || [[ -n "$proj" ]]; do
        [[ -z "$proj" ]] && continue
        local rel="${proj#./}"
        local manifest="$SCRIPT_DIR/$rel/homelab.yml"
        if [[ -f "$manifest" ]]; then
            local name; name=$(yaml_get "$manifest" "name")
            local subdomain; subdomain=$(yaml_get "$manifest" "subdomain")
            printf "  %-30s  name: %-20s  subdomain: %s\n" "$proj" "$name" "$subdomain"
        else
            echo "  $proj  (homelab.yml missing!)"
        fi
    done < "$PROJECTS_FILE"
}

# =========================
# Argument parsing
# =========================

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTION]

Run without options to perform initial stack setup (interactive),
including optional UFW firewall configuration.

Options:
  -a, --add-project <path>     Register a custom project and deploy its Caddy snippet
  -r, --remove-project <path>  Unregister a custom project and remove its Caddy snippet
  -l, --list-projects          List all registered custom projects
  -f, --setup-firewall         Configure UFW firewall rules (reads active profiles from .env)
  -h, --help                   Show this help message

Examples:
  ./setup.sh                        # Initial interactive setup (includes firewall)
  ./setup.sh -a ./my-project        # Add a custom project
  ./setup.sh -r ./my-project        # Remove a custom project
  ./setup.sh -l                     # List registered projects
  ./setup.sh -f                     # (Re-)configure UFW firewall
EOF
}

cmd_setup_firewall() {
    if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
        error "No .env found — run ./setup.sh first to create the initial configuration."
    fi
    PROFILES=$(grep "^COMPOSE_PROFILES=" "$SCRIPT_DIR/.env" | cut -d= -f2)
    if [[ -z "$PROFILES" ]]; then
        warn "COMPOSE_PROFILES not set in .env; only base rules (SSH, HTTP, HTTPS) will be applied."
    fi
    echo
    echo "========================================="
    echo "  UFW Firewall Setup"
    echo "========================================="
    echo
    setup_firewall
    echo
    echo "========================================="
    echo -e "${GREEN}  Firewall setup complete!${NC}"
    echo "========================================="
}

MODE="setup"
PROJECT_ARG=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -a|--add-project)
            MODE="add-project"
            PROJECT_ARG="${2:-}"
            [[ -n "$PROJECT_ARG" ]] && shift
            shift
            ;;
        -r|--remove-project)
            MODE="remove-project"
            PROJECT_ARG="${2:-}"
            [[ -n "$PROJECT_ARG" ]] && shift
            shift
            ;;
        -l|--list-projects)
            MODE="list-projects"
            shift
            ;;
        -f|--setup-firewall)
            MODE="setup-firewall"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            error "Unknown option: $1"
            ;;
    esac
done

# Dispatch sub-commands
case "$MODE" in
    add-project)    cmd_add_project    "$PROJECT_ARG"; exit 0 ;;
    remove-project) cmd_remove_project "$PROJECT_ARG"; exit 0 ;;
    list-projects)  cmd_list_projects;                 exit 0 ;;
    setup-firewall) cmd_setup_firewall;                exit 0 ;;
esac

# =========================
# Main setup flow
# =========================

echo "========================================="
echo "  Homelab Stack Setup"
echo "========================================="
echo

# Check if already configured
if [[ -f "$SCRIPT_DIR/.env" ]]; then
    warn "Configuration already exists (.env found)"
    read -p "Overwrite existing configuration? [y/N] " -n 1 -r
    echo
    [[ ! $REPLY =~ ^[Yy]$ ]] && exit 0
fi

# Prompt for configuration
read -p "Enter your domain [$DEFAULT_DOMAIN]: " DOMAIN
DOMAIN=${DOMAIN:-$DEFAULT_DOMAIN}

read -p "Enter data directory [$DEFAULT_DATA_DIR]: " DATA_DIR
DATA_DIR=${DATA_DIR:-$DEFAULT_DATA_DIR}

echo
echo "Select services to enable:"
read -p "  Enable Nextcloud? [Y/n] " -n 1 -r ENABLE_NEXTCLOUD
echo
read -p "  Enable UISP? [Y/n] " -n 1 -r ENABLE_UISP
echo
read -p "  Enable Jitsi? [Y/n] " -n 1 -r ENABLE_JITSI
echo
read -p "  Enable UniFi Controller? [Y/n] " -n 1 -r ENABLE_UNIFI
echo

# Build COMPOSE_PROFILES
PROFILES=""
[[ ! $ENABLE_NEXTCLOUD =~ ^[Nn]$ ]] && PROFILES="${PROFILES}nextcloud,"
[[ ! $ENABLE_UISP =~ ^[Nn]$ ]] && PROFILES="${PROFILES}uisp,"
[[ ! $ENABLE_JITSI =~ ^[Nn]$ ]] && PROFILES="${PROFILES}jitsi,"
[[ ! $ENABLE_UNIFI =~ ^[Nn]$ ]] && PROFILES="${PROFILES}unifi,"
PROFILES=${PROFILES%,}  # Remove trailing comma

# Prompt for MGMT subnet if UISP and/or UniFi are enabled
MGMT_ALLOWED_SUBNET="$DEFAULT_MGMT_SUBNET"
if [[ $PROFILES == *"uisp"* ]] || [[ $PROFILES == *"unifi"* ]]; then
    echo
    echo "Management GUI access restriction (recommended):"
    echo "  Provide ONE allowed subnet in CIDR (example: 192.168.2.0/24 or 172.16.1.0/24)."
    echo "  Leave blank to skip restriction (NOT recommended if exposed externally)."
    read -p "  Allowed subnet for UISP/UniFi GUIs [$DEFAULT_MGMT_SUBNET]: " MGMT_ALLOWED_SUBNET
    MGMT_ALLOWED_SUBNET=${MGMT_ALLOWED_SUBNET:-$DEFAULT_MGMT_SUBNET}

    # Basic CIDR sanity check (lightweight)
    if [[ -n "$MGMT_ALLOWED_SUBNET" ]] && [[ ! "$MGMT_ALLOWED_SUBNET" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[1-2][0-9]|3[0-2])$ ]]; then
        error "Invalid CIDR format: '$MGMT_ALLOWED_SUBNET' (expected e.g. 192.168.2.0/24)"
    fi
fi

# Secret generation
generate_secret() {
    openssl rand -base64 32 | tr -d '/+=' | cut -c1-32
}

prompt_secret() {
    local name="$1"
    local var_name="$2"
    local value=""

    read -p "  $name - generate random? [Y/n] " -n 1 -r generate
    echo
    if [[ $generate =~ ^[Nn]$ ]]; then
        read -p "    Enter $name: " -s value
        echo
        while [[ -z "$value" ]]; do
            echo "    Password cannot be empty"
            read -p "    Enter $name: " -s value
            echo
        done
    else
        value=$(generate_secret)
        echo "    (generated)"
    fi
    printf -v "$var_name" '%s' "$value"
}

echo
echo "Configure secrets:"

if [[ $PROFILES == *"nextcloud"* ]]; then
    echo
    echo "Nextcloud/MariaDB:"
    prompt_secret "MySQL password" MYSQL_PASSWORD
    prompt_secret "MySQL root password" MYSQL_ROOT_PASSWORD
fi

if [[ $PROFILES == *"jitsi"* ]]; then
    echo
    echo "Jitsi:"
    prompt_secret "Jicofo auth password" JICOFO_AUTH_PASSWORD
    prompt_secret "JVB auth password" JVB_AUTH_PASSWORD
fi

# Create root .env
info "Creating root .env..."

{
    cat << EOF
# Base domain for all services
BASE_DOMAIN=$DOMAIN

# Data directory for all persistent storage
DATA_DIR=$DATA_DIR

# Services to enable (comma-separated: nextcloud,uisp,jitsi,unifi)
# Caddy always runs as it's the reverse proxy
COMPOSE_PROFILES=$PROFILES
EOF

    # Only add management subnet if UISP and/or UniFi are enabled
    if [[ $PROFILES == *"uisp"* ]] || [[ $PROFILES == *"unifi"* ]]; then
        cat << EOF

# Restrict management GUIs (UISP + UniFi) to a single subnet (CIDR)
# Example: 192.168.2.0/24
MGMT_ALLOWED_SUBNET=$MGMT_ALLOWED_SUBNET
EOF
    fi
} > "$SCRIPT_DIR/.env"

# Create nextcloud .env files
if [[ $PROFILES == *"nextcloud"* ]]; then
    info "Creating nextcloud/.env..."
    sed "s/\${BASE_DOMAIN}/$DOMAIN/g" "$SCRIPT_DIR/nextcloud/.env.example" > "$SCRIPT_DIR/nextcloud/.env"

    info "Creating nextcloud/.env.secrets..."
    cat > "$SCRIPT_DIR/nextcloud/.env.secrets" << EOF
MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
EOF
fi

# Create jitsi .env files
if [[ $PROFILES == *"jitsi"* ]]; then
    info "Creating jitsi-deploy/.env..."
    sed "s/\${BASE_DOMAIN}/$DOMAIN/g" "$SCRIPT_DIR/jitsi-deploy/.env.example" > "$SCRIPT_DIR/jitsi-deploy/.env"

    info "Creating jitsi-deploy/.env.secrets..."
    cat > "$SCRIPT_DIR/jitsi-deploy/.env.secrets" << EOF
JICOFO_AUTH_USER=focus
JVB_AUTH_USER=jvb
JICOFO_AUTH_PASSWORD=$JICOFO_AUTH_PASSWORD
JVB_AUTH_PASSWORD=$JVB_AUTH_PASSWORD
EOF
fi

# Create data directories
info "Creating data directories in $DATA_DIR..."
sudo mkdir -p "$DATA_DIR/caddy/data"
sudo mkdir -p "$DATA_DIR/caddy/config"
sudo mkdir -p "$DATA_DIR/caddy/conf.d"

if [[ $PROFILES == *"nextcloud"* ]]; then
    if [[ -d "$DATA_DIR/nextcloud/html" ]]; then
        info "Nextcloud html directory exists, skipping (existing installation)"
    else
        sudo mkdir -p "$DATA_DIR/nextcloud/html"
        sudo mkdir -p "$DATA_DIR/nextcloud/data"
        sudo mkdir -p "$DATA_DIR/nextcloud/db"
        sudo mkdir -p "$DATA_DIR/nextcloud/redis"
    fi
fi

if [[ $PROFILES == *"uisp"* ]]; then
    sudo mkdir -p "$DATA_DIR/uisp/data"
    sudo mkdir -p "$DATA_DIR/uisp/logs"
fi

if [[ $PROFILES == *"jitsi"* ]]; then
    sudo mkdir -p "$DATA_DIR/jitsi/web"
    sudo mkdir -p "$DATA_DIR/jitsi/web-public"
    sudo mkdir -p "$DATA_DIR/jitsi/prosody"
    sudo mkdir -p "$DATA_DIR/jitsi/jicofo"
    sudo mkdir -p "$DATA_DIR/jitsi/jvb"
    sudo mkdir -p "$DATA_DIR/jitsi/branding"
fi

if [[ $PROFILES == *"unifi"* ]]; then
    sudo mkdir -p "$DATA_DIR/unifi/data"
fi

# Copy Caddyfile
info "Copying Caddyfile to $DATA_DIR/caddy/..."
sudo cp "$SCRIPT_DIR/caddy/Caddyfile" "$DATA_DIR/caddy/Caddyfile"

# Deploy caddy snippets for any registered custom projects
deploy_caddy_snippets "$DATA_DIR"

# Copy Jitsi branding
if [[ $PROFILES == *"jitsi"* ]]; then
    info "Copying Jitsi branding to $DATA_DIR/jitsi/branding/..."
    sudo cp "$SCRIPT_DIR/jitsi-deploy/branding/watermark.svg" "$DATA_DIR/jitsi/branding/watermark.svg"
fi

# Set permissions
info "Setting permissions..."

# Caddy: runs as root, config files read-only
sudo chown -R root:root "$DATA_DIR/caddy"
sudo chmod 755 "$DATA_DIR/caddy"
sudo chmod 644 "$DATA_DIR/caddy/Caddyfile"
sudo chmod 755 "$DATA_DIR/caddy/data" "$DATA_DIR/caddy/config" "$DATA_DIR/caddy/conf.d"

if [[ $PROFILES == *"nextcloud"* ]]; then
    # Secret files: restrict access
    chmod 600 "$SCRIPT_DIR/nextcloud/.env.secrets"

    # Only set permissions for fresh installs (skip if config.php exists)
    if [[ ! -f "$DATA_DIR/nextcloud/html/config/config.php" ]]; then
        # Nextcloud: runs as www-data (33:33)
        sudo chown -R 33:33 "$DATA_DIR/nextcloud/html"
        sudo chown -R 33:33 "$DATA_DIR/nextcloud/data"
        sudo chmod 750 "$DATA_DIR/nextcloud/html" "$DATA_DIR/nextcloud/data"

        # MariaDB: runs as mysql (999:999)
        sudo chown -R 999:999 "$DATA_DIR/nextcloud/db"
        sudo chmod 750 "$DATA_DIR/nextcloud/db"

        # Redis: runs as redis (999:999)
        sudo chown -R 999:999 "$DATA_DIR/nextcloud/redis"
        sudo chmod 750 "$DATA_DIR/nextcloud/redis"
    else
        info "Nextcloud config.php exists, skipping permission changes"
    fi
fi

if [[ $PROFILES == *"uisp"* ]]; then
    # UISP: runs as root
    sudo chown -R root:root "$DATA_DIR/uisp"
    sudo chmod 755 "$DATA_DIR/uisp/data" "$DATA_DIR/uisp/logs"
fi

if [[ $PROFILES == *"jitsi"* ]]; then
    # Jitsi: runs as root
    sudo chown -R root:root "$DATA_DIR/jitsi"
    sudo chmod 755 "$DATA_DIR/jitsi/web" "$DATA_DIR/jitsi/web-public"
    sudo chmod 755 "$DATA_DIR/jitsi/prosody" "$DATA_DIR/jitsi/jicofo" "$DATA_DIR/jitsi/jvb"
    sudo chmod 755 "$DATA_DIR/jitsi/branding"
    sudo chmod 644 "$DATA_DIR/jitsi/branding/watermark.svg"

    # Secret files: restrict access
    chmod 600 "$SCRIPT_DIR/jitsi-deploy/.env.secrets"
fi

if [[ $PROFILES == *"unifi"* ]]; then
    # UniFi: runs as unifi user (999:999)
    sudo chown -R 999:999 "$DATA_DIR/unifi/data"
    sudo chmod 750 "$DATA_DIR/unifi/data"
fi

echo
echo "========================================="
echo -e "${GREEN}  Setup complete!${NC}"
echo "========================================="
echo
echo "Configuration summary:"
echo "  Domain:     $DOMAIN"
echo "  Data dir:   $DATA_DIR"
echo "  Services:   $PROFILES"
[[ -n "$MGMT_ALLOWED_SUBNET" ]] && echo "  Mgmt subnet: $MGMT_ALLOWED_SUBNET"
echo
echo "Service URLs:"
[[ $PROFILES == *"nextcloud"* ]] && echo "  Nextcloud:  https://nextcloud.$DOMAIN"
[[ $PROFILES == *"uisp"* ]] && echo "  UISP:       https://uisp.$DOMAIN"
[[ $PROFILES == *"jitsi"* ]] && echo "  Jitsi:      https://meet.$DOMAIN"
[[ $PROFILES == *"jitsi"* ]] && echo "  Jitsi Admin: https://adm.meet.$DOMAIN"
[[ $PROFILES == *"unifi"* ]] && echo "  UniFi:      https://unifi.$DOMAIN"
echo
echo "Next steps:"
echo "  1. Review generated config files"
[[ $PROFILES == *"jitsi"* ]] && echo "  2. Customize Jitsi logo: $DATA_DIR/jitsi/branding/watermark.svg"
echo "  3. Start the stack: docker compose up -d"
echo "  4. Check logs: docker compose logs -f"
echo
[[ $PROFILES == *"nextcloud"* ]] && echo "Migrating existing Nextcloud? See README.md for steps."
echo "Add custom projects: ./setup.sh --add-project <path>"
echo

# ----------------------------
# Firewall (UFW) setup
# ----------------------------
setup_firewall() {
  local BASE_RULES=(
    "22/tcp:SSH"
    "80/tcp:HTTP"
    "443/tcp:HTTPS"
  )
  local RULES_NEXTCLOUD=()
  local RULES_UISP=(
    "2055/udp:NetFlow/UDP 2055"
  )
  local RULES_JITSI=(
    "10000/udp:Jitsi JVB Media"
  )
  local RULES_UNIFI=(
    "3478/udp:UniFi STUN"
    "10001/udp:UniFi Device Discovery"
    "8080/tcp:UniFi Inform (Adoption)"
  )

  local DESIRED_RULES=()
  DESIRED_RULES+=( "${BASE_RULES[@]}" )

  IFS=',' read -r -a profiles_arr <<< "$PROFILES"
  local p
  for p in "${profiles_arr[@]}"; do
    case "$p" in
      nextcloud) DESIRED_RULES+=( "${RULES_NEXTCLOUD[@]}" ) ;;
      uisp)      DESIRED_RULES+=( "${RULES_UISP[@]}" ) ;;
      jitsi)     DESIRED_RULES+=( "${RULES_JITSI[@]}" ) ;;
      unifi)     DESIRED_RULES+=( "${RULES_UNIFI[@]}" ) ;;
      "")        ;;
      *)         warn "Unknown profile '$p'; ignoring for firewall rules." ;;
    esac
  done

  local seen="" out=() rule portproto
  for rule in "${DESIRED_RULES[@]}"; do
    portproto="${rule%%:*}"
    if [[ ",$seen," != *",$portproto,"* ]]; then
      out+=( "$rule" )
      seen="${seen},${portproto}"
    fi
  done
  DESIRED_RULES=( "${out[@]}" )

  info "Desired firewall allow rules:"
  for r in "${DESIRED_RULES[@]}"; do
    echo "  - ${r%%:*}  (${r##*:})"
  done
  echo

  if ! command -v ufw >/dev/null 2>&1; then
    warn "ufw is not installed."
    read -p "Install ufw now via apt-get? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      sudo apt-get update
      sudo apt-get install -y ufw
      info "ufw installed."
    else
      warn "ufw is required for firewall setup. Skipping."
      return 0
    fi
  else
    info "ufw is installed: $(sudo ufw --version | head -n1 || true)"
  fi

  local status_verbose
  status_verbose="$(sudo ufw status verbose 2>/dev/null || true)"

  local existing desired
  existing="$(awk '
    BEGIN{IGNORECASE=1}
    NR>2 && $1 !~ /^(Status:|To)$/ {
      to=$1; action=$2
      if (action != "ALLOW") next
      split(to, a, "/")
      port=a[1]; proto=a[2]
      if (port ~ /^[0-9]+$/ && proto ~ /^(tcp|udp)$/)
        print proto ":" port
    }
  ' <<<"$status_verbose" | sort -u)"

  desired="$(for rule in "${DESIRED_RULES[@]}"; do
    portproto="${rule%%:*}"
    port="${portproto%%/*}"
    proto="${portproto##*/}"
    echo "${proto}:${port}"
  done | sort -u)"

  local incoming outgoing
  read -r incoming outgoing < <(awk -F': ' '/Default: /{print $2}' <<<"$status_verbose" \
    | awk -F', ' '{print $1, $2}' | xargs || true)

  local defaults_ok=0
  if [[ "${incoming,,}" == "deny (incoming)" || "${incoming,,}" == "deny" ]] && \
     [[ "${outgoing,,}" == "allow (outgoing)" || "${outgoing,,}" == "allow" ]]; then
    defaults_ok=1
  fi

  if [[ "$existing" == "$desired" ]] && [[ "$defaults_ok" -eq 1 ]]; then
    info "UFW already matches the desired rule set and default policies. No changes needed."
    return 0
  fi

  local ipv6_setting="unknown"
  if [[ -f /etc/default/ufw ]]; then
    ipv6_setting="$(grep -E '^[[:space:]]*IPV6=' /etc/default/ufw | tail -n1 | cut -d= -f2- | tr -d '[:space:]' || true)"
    ipv6_setting="${ipv6_setting,,}"
    [[ "$ipv6_setting" != "yes" && "$ipv6_setting" != "no" ]] && ipv6_setting="unknown"
  fi
  info "Current UFW IPv6 setting: IPV6=${ipv6_setting}"
  if [[ "$ipv6_setting" != "yes" ]]; then
    warn "IPv6 is not enabled for UFW. IPv6 allow rules may not be applied."
    read -p "Set IPV6=yes in /etc/default/ufw (backup will be created)? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      local ufw_conf="/etc/default/ufw"
      sudo cp -a "$ufw_conf" "${ufw_conf}.bak.$(date +%Y%m%d%H%M%S)"
      if grep -qE '^[[:space:]]*IPV6=' "$ufw_conf"; then
        sudo sed -i 's/^[[:space:]]*IPV6=.*/IPV6=yes/' "$ufw_conf"
      else
        echo "IPV6=yes" | sudo tee -a "$ufw_conf" >/dev/null
      fi
      info "Set IPV6=yes."
    else
      warn "Keeping IPV6 unchanged."
    fi
  fi

  info "Current UFW status:"
  sudo ufw status verbose || true
  echo

  read -p "Reset UFW (removes existing rules) before applying? [y/N] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo ufw --force reset
    info "UFW reset complete."
  else
    warn "Skipping reset. Will add rules on top of existing configuration."
  fi

  if [[ "$defaults_ok" -eq 0 ]]; then
    warn "Default policies are not as expected."
    read -p "Set default incoming=deny, outgoing=allow? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      sudo ufw default deny incoming
      sudo ufw default allow outgoing
    else
      warn "Leaving default policies unchanged."
    fi
  else
    info "Default policies already match (deny incoming, allow outgoing)."
  fi

  read -p "Apply the desired allow rules now? [y/N] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    for rule in "${DESIRED_RULES[@]}"; do
      local port_proto="${rule%%:*}"
      local comment="${rule##*:}"
      sudo ufw allow "$port_proto" comment "$comment"
    done
    info "Allow rules applied."
  else
    warn "Skipping allow rules."
  fi

  read -p "Enable UFW now? [y/N] " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo ufw --force enable
    info "UFW enabled."
  else
    warn "UFW was not enabled."
  fi

  echo
  info "Final UFW status:"
  sudo ufw status verbose || true
}

# Ask if user wants to set up firewall
echo
read -p "Configure UFW firewall now? [y/N] " -n 1 -r SETUP_FIREWALL
echo
if [[ $SETUP_FIREWALL =~ ^[Yy]$ ]]; then
  echo
  echo "========================================="
  echo "  UFW Firewall Setup"
  echo "========================================="
  echo
  setup_firewall
  echo
  echo "========================================="
  echo -e "${GREEN}  Firewall setup complete!${NC}"
  echo "========================================="
fi
